export const HomePageSEO = {
  title: "Altmate",
  description:
    "Enhance your web content’s accessibility and SEO with Altmate’s AI-powered alt text generator. Create descriptive, SEO-friendly alt text in seconds for optimized search visibility.",
};

export const FeaturesPage = {
  title: "Altmate | Modern AI features for Enhanced Alt Text",
  description:
    "Discover Altmate's advanced features for crafting SEO-optimized, accessible alt text. Our AI features offer accuracy, customization, and efficiency for better web presence.",
};

export const PricingPage = {
  title: "Altmate | Affordable Alt Text Generator Plans",
  description:
    "Choose simple, affordable one-time pricing plans for Altmate’s AI-powered alt text generator. No subscriptions—pay once for seamless alt text creation.",
};

export const ExamplesPage = {
  title: "Altmate | Examples",
  description:
    "Explore example alt texts generated by Altmate's AI. See how descriptive, SEO-friendly alt text can improve your site’s accessibility and search rankings.",
};

export const DashboardPage = {
  title: "Altmate | Dashboard",
};

export const AltTextsPage = {
  title: "Altmate | Alt Texts",
};

export const GenerateAltTextPage = {
  title: "Altmate | Generate Alt Text",
};

export const LoginPage = {
  title: "Altmate | Login",
};

export const SignupPage = {
  title: "Altmate | Sign up",
};

export const ResetPasswordPage = {
  title: "Altmate | Reset Password",
};

export const ChangePasswordPage = {
  title: "Altmate | Change Password",
};
