import Container from "@/components/container";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export function NewsletterSection() {
  return (
    <Container>
      <div className="w-full">
        <p className="mb-2 text-muted-foreground">FAQ</p>
        <h2 className="w-full text-4xl max-md:text-3xl font-bold mb-16">
          Common question answered.
        </h2>
      </div>
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1">
          <AccordionTrigger className="font-semibold text-lg">
            How does AI generate alt text from my images?
          </AccordionTrigger>
          <AccordionContent className="text-base text-muted-foreground">
            Our AI alt text generator uses advanced artificial intelligence to
            analyze the content of your images and create accurate, context-rich
            alt text descriptions that enhance accessibility and SEO.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-2">
          <AccordionTrigger className="font-semibold text-lg">
            What types of images can I upload?
          </AccordionTrigger>
          <AccordionContent className="text-base text-muted-foreground">
            You can upload various image formats, including JPEG, PNG, and GIF,
            to our AI alt text generator. This ensures that any image you need
            alt text for is easily processed.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-3">
          <AccordionTrigger className="font-semibold text-lg">
            Is there a limit on image size or quantity?
          </AccordionTrigger>
          <AccordionContent className="text-base text-muted-foreground">
            While there are no restrictions on the number of images you can
            upload to the AI alt text generator, we recommend keeping individual
            file sizes under 10 MB for optimal performance and speed.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-4">
          <AccordionTrigger className="font-semibold text-lg">
            How accurate is the alt text generated by AI?
          </AccordionTrigger>
          <AccordionContent className="text-base text-muted-foreground">
            The AI alt text generator is designed to provide highly accurate alt
            text descriptions by understanding the context of your images,
            ensuring that your content is accessible and SEO-friendly.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-5">
          <AccordionTrigger className="font-semibold text-lg">
            How long does it take to generate alt text?
          </AccordionTrigger>
          <AccordionContent className="text-base text-muted-foreground">
            The AI alt text generator quickly produces alt text, typically
            within seconds after uploading your image, allowing you to enhance
            your website's accessibility and search engine optimization without
            delay.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </Container>
  );
}
